### ISSUE TITLE
Where did the notes attribute go?

### ISSUE THREAD

**Issue by SergeoLacruz** [inventree/inventree-python#259]
Since update to 17 the notes attribute on parts has vanished. The following does not work any longer:
```
part_to_update.save({ 'notes': 'Hello'})
print(part_to_update.notes)
```

AttributeError: 'Part' object has no attribute 'notes'

Any idea?

**Comment by miggland** [comment]
How did you get the part, through list(), or directly with a defined pk?

See this issue, it could be related: https://github.com/inventree/InvenTree/issues/8672

The difference in that case is not in  `inventree-python`, but in the API..

**Comment by SergeoLacruz** [comment]
via Part.list(api) and then some further search in the list.

**Comment by miggland** [comment]
Probably you will be able to access the note if do something like
```
part_to_update = Part(api, pk=14)
```

**Comment by SergeoLacruz** [comment]
In that way it works. Strange...
Thanks for the hint :-)

**Comment by miggland** [comment]
Yes, I agree. The reason is that getting a single item and the listing use different API endpoints.

The listing does not return notes, whereas the single item endpoint does, thus https://github.com/inventree/InvenTree/issues/8672 ..
